const controls=[['Stick','Analog stick'],['Stick press in','Center press'],['Center button','PS button'],['Button 1','Top-left'],['Button 2','Top-right'],['Button 3','Left'],['Button 4','Right'],['Button 5','Bottom-left'],['Button 6','Bottom-right'],['Button 7','Front-left'],['Button 8','Front-right'],['Expansion port 1','External switch'],['Expansion port 2','External switch'],['Expansion port 3','External switch'],['Expansion port 4','External switch']];
const actions=['Nothing','Circle','Cross','Triangle','Square','D-pad up','D-pad down','D-pad left','D-pad right','L1','R1','L2','R2','L3','R3','Options','Create','PS button','Touch pad','Left stick','Right stick'];
const icons={'Nothing':'—','Circle':'🔴','Cross':'✖️','Triangle':'🔺','Square':'🟦','D-pad up':'⬆️','D-pad down':'⬇️','D-pad left':'⬅️','D-pad right':'➡️','L1':'L¹','R1':'R¹','L2':'L²','R2':'R²','L3':'L³','R3':'R³','Options':'☰','Create':'▣','PS button':'PS','Touch pad':'▤','Left stick':'🕹️','Right stick':'🕹️'};
const androidLabels={'Nothing':'Unassigned','Triangle':'X','Circle':'A','Cross':'B','Square':'Square','D-pad up':'D-pad up','D-pad down':'D-pad down','D-pad left':'D-pad left','D-pad right':'D-pad right','L1':'Y','R1':'R1','L2':'LB','R2':'RB','L3':'Select','R3':'Select','Options':'RT','Create':'LT','PS button':'Home','Touch pad':'L3','Left stick':'Left stick','Right stick':'Right stick'};
const actionId=x=>x==='Left stick'?101:x==='Right stick'?102:actions.indexOf(x),actionLabel=x=>x===101?'Left stick':x===102?'Right stick':actions[x]||'Nothing';
const meta=[{p:0},{b:10},{b:9},...Array.from({length:8},(_,i)=>({b:i+1})),...Array.from({length:4},(_,i)=>({p:i+1}))];
const profiles=Array.from({length:3},()=>({orientation:'3',mappings:controls.map(()=>({action:'Nothing',toggle:false,analog:false})),raw:null}));let active=0,device=null,actionStyle='playstation',testFrame=null;
const list=document.querySelector('#mapping-list'),profileName=document.querySelector('#profile-name'),orientation=document.querySelector('#orientation'),status=document.querySelector('#status');
function render(){const p=profiles[active];profileName.textContent=`Profile ${active+1}`;orientation.value=p.orientation;document.querySelector('#action-style').value=actionStyle;document.querySelectorAll('.profile-tab').forEach((e,i)=>e.classList.toggle('active',i===active));list.innerHTML=controls.map(([n,d],i)=>{const m=p.mappings[i],port=i>10;return `<article class="mapping-row"><div><div class="control-name">${n}</div><div class="control-detail">${d}</div></div><select class="mapping-select" data-action="${i}" aria-label="Action for ${n}">${actions.map(a=>`<option value="${a}" ${m.action===a?'selected':''}>${icons[a]}  ${actionStyle==='android'?androidLabels[a]:a}</option>`).join('')}</select><div class="options"><label class="option"><input type="checkbox" data-toggle="${i}" ${m.toggle?'checked':''}> Toggle</label>${port?`<label class="option"><input type="checkbox" data-analog="${i}" ${m.analog?'checked':''}> Analog</label>`:''}</div></article>`}).join('')}
function connection(ok,msg){document.querySelector('#connection-card').classList.toggle('connected',ok);document.querySelector('#connection-text').textContent=ok?'Access controller connected':'Controller not connected';document.querySelector('#connect-button').textContent=ok?'Disconnect controller':'Connect controller';document.querySelector('#save-button').disabled=!ok;status.textContent=msg}
const gamepadActions=['Cross','Circle','Square','Triangle','L1','R1','L2','R2','Create','Options','L3','R3','D-pad up','D-pad down','D-pad left','D-pad right','PS button','Touch pad'];
function stopTest(){if(testFrame===null)return;cancelAnimationFrame(testFrame);testFrame=null;document.querySelector('#test-button').textContent='Test controller';status.textContent='Input test stopped.'}
function startTest(){const poll=()=>{const pad=[...navigator.getGamepads()].find(p=>p&&(/access|sony|playstation/i.test(p.id)));if(!pad){status.textContent='Waiting for the controller input interface… press a controller button.'}else{const pressed=pad.buttons.flatMap((b,i)=>b.pressed||b.value>.5?[gamepadActions[i]||`Button ${i+1}`]:[]);const sticks=[];if(Math.abs(pad.axes[0]||0)>.2||Math.abs(pad.axes[1]||0)>.2)sticks.push('Left stick');if(Math.abs(pad.axes[2]||0)>.2||Math.abs(pad.axes[3]||0)>.2)sticks.push('Right stick');const input=[...pressed,...sticks];status.textContent=input.length?`Live input: ${input.join(', ')}`:'Input test active — press a controller button.'}testFrame=requestAnimationFrame(poll)};document.querySelector('#test-button').textContent='Stop test';status.textContent='Input test active — press a controller button.';poll()}
async function connect(){if(device){await device.close();device=null;connection(false,'Controller disconnected.');return}if(!('hid'in navigator)){status.textContent='WebHID is unavailable. Use Chrome or Edge on desktop, opened through localhost.';return}try{const d=await navigator.hid.requestDevice({filters:[{vendorId:0x054c,productId:0x0e5f}]});if(!d.length){status.textContent='No Access controller was selected.';return}device=d[0];if(!device.opened)await device.open();if(device.collections[0]?.featureReports?.some(x=>x.reportId===99))throw new Error('Connect the Access controller with a USB cable, not Bluetooth.');connection(true,'Connected over USB. Load profiles before editing.')}catch(e){device=null;connection(false,e.message||String(e))}}
function readProfile(pi,bytes){if(bytes[0]!==2)throw new Error(`Profile ${pi+1} returned unexpected data.`);const p=profiles[pi];p.raw=bytes;meta.forEach((x,i)=>{const m=p.mappings[i];if(x.b){const n=x.b;m.action=actionLabel(bytes[100+(n-1)*5]);m.toggle=!!(bytes[150+Math.floor((n-1)/8)]&(1<<((n-1)%8)))}else{const at=152+x.p*45,type=bytes[at],bit=9+x.p;m.toggle=!!(bytes[150+Math.floor(bit/8)]&(1<<(bit%8)));m.analog=type===2;m.action=type===1?actionLabel(100+bytes[at+1]):actionLabel(bytes[at+2]);if(x.p===0&&type===1)p.orientation=String(bytes[at+2])}})}
async function load(){if(!device){status.textContent='Connect an Access controller first.';return}try{for(let p=0;p<3;p++){const req=new Uint8Array(63);req[0]=0x10+p;await device.sendFeatureReport(0x60,req);const data=new Uint8Array(956);for(let i=0;i<18;i++){const report=await device.receiveFeatureReport(0x61);for(let j=0;j<56&&i*56+j<956;j++)data[i*56+j]=report.getUint8(4+j)}readProfile(p,data)}render();status.textContent='All three profiles loaded from controller.'}catch(e){status.textContent=`Could not load profiles: ${e.message||e}`}}
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function build(pi){const p=profiles[pi];if(!p.raw)throw new Error('Load profiles first so unedited controller settings are preserved.');const bytes=new Uint8Array(p.raw),view=new DataView(bytes.buffer);let toggle=bytes[150]|bytes[151]<<8;meta.forEach((x,i)=>{const m=p.mappings[i],id=actionId(m.action);if(x.b){const n=x.b;bytes[100+(n-1)*5]=id;toggle=m.toggle?toggle|(1<<(n-1)):toggle&~(1<<(n-1))}else{const at=152+x.p*45,bit=9+x.p;toggle=m.toggle?toggle|(1<<bit):toggle&~(1<<bit);if(id>=101){bytes[at]=1;bytes[at+1]=id-100;bytes[at+2]=+p.orientation}else{bytes[at]=m.analog?2:3;bytes[at+2]=id}}});bytes[150]=toggle&255;bytes[151]=toggle>>8;view.setBigInt64(948,BigInt(Date.now()),true);return bytes}
async function save(){if(!device)return;try{for(let p=0;p<3;p++){const bytes=build(p);for(let i=0;i<18;i++){const report=new Uint8Array(63);report[0]=0x09+p;report[1]=i;report.set(bytes.slice(i*56,i*56+56),2);if(i===17)new DataView(report.buffer).setUint32(6,crc32(bytes),true);await device.sendFeatureReport(0x60,report)}}status.textContent='All profile changes saved to controller.'}catch(e){status.textContent=`Could not save profiles: ${e.message||e}`}}
document.querySelectorAll('.profile-tab').forEach(e=>e.onclick=()=>{active=+e.dataset.profile;render()});orientation.onchange=()=>profiles[active].orientation=orientation.value;document.querySelector('#action-style').onchange=e=>{actionStyle=e.target.value;render()};list.onchange=e=>{const i=+(e.target.dataset.action??e.target.dataset.toggle??e.target.dataset.analog),m=profiles[active].mappings[i];if(e.target.dataset.action!==undefined)m.action=e.target.value;if(e.target.dataset.toggle!==undefined)m.toggle=e.target.checked;if(e.target.dataset.analog!==undefined)m.analog=e.target.checked};document.querySelector('#connect-button').onclick=connect;document.querySelector('#load-button').onclick=load;document.querySelector('#save-button').onclick=save;if('hid'in navigator)navigator.hid.addEventListener('disconnect',e=>{if(e.device===device){device=null;connection(false,'Controller disconnected.')}});const dialog=document.querySelector('#readme-dialog');document.querySelector('#readme-button').onclick=()=>dialog.showModal();document.querySelector('#close-dialog').onclick=()=>dialog.close();render();
document.querySelector('#test-button').onclick=()=>testFrame!==null?stopTest():startTest();
